version: '3.0'

services:
  grafana:
    container_name: 'mckn-funnel-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.0.0}
    environment:
      - GF_USERS_DEFAULT_THEME=system
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/mckn-funnel-panel
      - ./provisioning:/etc/grafana/provisioning
